[project]
name = "smart-agent-assignments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-generativeai>=0.8.5",
    "litellm>=1.74.7",
    "openai-agents>=0.2.2",
]
